### ISSUE TITLE
项目通过jar 包方式上传到服务器后 ，autopoi 读取不到jar包里的excel模版文件 （导出功能）

### ISSUE THREAD

**Issue by lihanxie** [zhangdaiscott/autopoi#23]
通过jar 包方式上传到服务器后 autopoi 读取不到jar包里的excel模版文件 
    TemplateExportParams params = new TemplateExportParams();
    params.setTemplateUrl(**relativePath**);
    params.setScanAllsheet(true);
    ModelAndView mv = new ModelAndView(new JeecgTemplateExcelView());
    mv.addObject(TemplateExcelConstants.MAP_DATA, productMap);
    mv.addObject(TemplateExcelConstants.FILE_NAME, templateName);
    mv.addObject(TemplateExcelConstants.PARAMS, params);
    mv.addObject(TemplateExcelConstants.CLASS, TBaseProductEntity.class);

2020-07-24 15:34:59.452 [http-nio-6080-exec-9] ERROR org.jeecgframework.poi.cache.manager.FileLoade:58 - home/eps/jeecg-boot/tts-module-system-2.2.0.jar!/BOOT-INF/classes!/import/订单导入/FBA订单模板.xlsx (没有那个文件或目录)
java.io.FileNotFoundException: home/eps/jeecg-boot/tts-module-system-2.2.0.jar!/BOOT-INF/classes!/import/订单导入/FBA订单模板.xlsx (没有那个文件或目录)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.(FileInputStream.java:138)
at java.io.FileInputStream.(FileInputStream.java:93)
at org.jeecgframework.poi.cache.manager.FileLoade.getFile(FileLoade.java:47)
at org.jeecgframework.poi.cache.manager.POICacheManager$1.load(POICacheManager.java:48)
at org.jeecgframework.poi.cache.manager.POICacheManager$1.load(POICacheManager.java:45)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
at org.jeecgframework.poi.cache.manager.POICacheManager.getFile(POICacheManager.java:56)

放置了excel模版在resources 中， IDEA 中运行是可以成功下载excel 模版文件的， 但是打包jar 放到服务器后就不行

**Comment by wangzhengyr** [comment]
请问这个问题解决了吗

**Comment by chency-jn** [comment]
我是这样写的 部署没问题
 String templatePath = "excel/trace_temp.xlsx";
Workbook workbook = ExcelExportUtil.exportExcel(new TemplateExportParams(templatePath, dataType), mapData);

**Comment by zhangdaiscott** [comment]
你用的那个模板

**Comment by zhangdaiscott** [comment]
已经解决了

**Comment by jaedongjuly** [comment]
现在版本还是有问题 jeecg-boot 2.4.5
